# Generated by Django 5.1.7 on 2025-04-01 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportFile",
            fields=[
                ("ReportId", models.BigAutoField(primary_key=True, serialize=False)),
                ("ReportName", models.CharField(max_length=200, null=True)),
                ("ReportDescription", models.CharField(max_length=1000, null=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportFileDetail",
            fields=[
                (
                    "ReportDetailId",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("FilterName", models.CharField(max_length=200, null=True)),
                ("FilterType", models.CharField(max_length=1000, null=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "ReportId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Report.reportfile",
                    ),
                ),
            ],
        ),
    ]
