# Generated by Django 5.1.7 on 2025-04-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportfile",
            name="ReportGroup",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
