# Generated by Django 5.1.7 on 2025-04-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Report", "0002_reportfile_reportgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportfile",
            name="SPObjectName",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
