# Generated by Django 5.1.7 on 2025-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_alter_reportfile_botto1left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='Botto1Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom1Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom2Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom2Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom3Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom3Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom4Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom4Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom5Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Bottom5Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top1Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top1Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top2Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top2Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top3Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top3Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top4Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top4Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top5Left',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='Top5Right',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
