# Generated by Django 5.1.7 on 2026-04-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0007_alter_reportfile_botto1left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportColumnDefinition',
            fields=[
                ('ReportColumnId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ColumnName', models.CharField(max_length=200)),
                ('DisplayName', models.CharField(blank=True, max_length=200, null=True)),
                ('DataType', models.CharField(blank=True, max_length=100, null=True)),
                ('ColumnWidth', models.FloatField(blank=True, null=True)),
                ('SortOrder', models.IntegerField(default=0)),
                ('isVisible', models.BooleanField(default=True)),
                ('ReportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.reportfile')),
            ],
            options={
                'ordering': ['SortOrder', 'ReportColumnId'],
            },
        ),
    ]
