# Generated by Django 5.1.7 on 2026-04-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0008_reportcolumndefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumndefinition',
            name='LoadSide',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default='LEFT', max_length=10),
        ),
    ]
