# Generated by Django 5.1.7 on 2025-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessSetting',
            fields=[
                ('SettingId', models.BigAutoField(primary_key=True, serialize=False)),
                ('EndpointAddress', models.CharField(max_length=200, null=True)),
                ('InvalidAccountLedger', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
