# Generated by Django 5.1.7 on 2025-09-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocesssetting',
            name='EndpointAddress2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
