# Generated by Django 5.1.7 on 2025-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileProcessing', '0002_fileprocesssetting_endpointaddress2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocesssetting',
            name='Coredatabase',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileprocesssetting',
            name='Corehost',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileprocesssetting',
            name='Corepassword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileprocesssetting',
            name='Coreport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileprocesssetting',
            name='Coreusername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
