# Generated by Django 5.1.7 on 2025-12-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileProcessing', '0003_fileprocesssetting_coredatabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocesssetting',
            name='DefaultODProduct',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
